INFO 2024-03-27 19:56:10,980 autoreload 17024 2200 Watching for file changes with StatReloader
INFO 2024-03-27 19:56:17,061 basehttp 17024 1760 "GET /taskApp/task1/ HTTP/1.1" 200 13
INFO 2024-03-27 20:01:40,737 autoreload 17024 2200 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\seminars\settings.py changed, reloading.
INFO 2024-03-27 20:01:41,325 autoreload 3668 19648 Watching for file changes with StatReloader
INFO 2024-03-27 20:01:49,571 views 3668 11928 Index page accessed
INFO 2024-03-27 20:01:49,572 basehttp 3668 11928 "GET /taskApp/task1/ HTTP/1.1" 200 13
INFO 2024-03-27 20:12:03,753 autoreload 3668 19648 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksApp\views.py changed, reloading.
INFO 2024-03-27 20:12:04,515 autoreload 17152 11512 Watching for file changes with StatReloader
INFO 2024-03-27 20:13:29,044 autoreload 17152 11512 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksApp\views.py changed, reloading.
INFO 2024-03-27 20:13:29,696 autoreload 21388 13060 Watching for file changes with StatReloader
INFO 2024-03-27 20:15:52,462 autoreload 21388 13060 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksApp\views.py changed, reloading.
INFO 2024-03-27 20:15:53,317 autoreload 18052 17884 Watching for file changes with StatReloader
INFO 2024-03-27 20:20:43,403 autoreload 18052 17884 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksApp\urls.py changed, reloading.
INFO 2024-03-27 20:20:43,971 autoreload 14408 21040 Watching for file changes with StatReloader
INFO 2024-03-27 20:21:00,192 basehttp 14408 18448 "GET /taskApp/main HTTP/1.1" 301 0
ERROR 2024-03-27 20:21:00,368 log 14408 10564 Internal Server Error: /taskApp/main/
Traceback (most recent call last):
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'str' object has no attribute 'get'
ERROR 2024-03-27 20:21:00,369 basehttp 14408 10564 "GET /taskApp/main/ HTTP/1.1" 500 65962
INFO 2024-03-27 20:22:17,013 autoreload 14408 21040 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksApp\views.py changed, reloading.
INFO 2024-03-27 20:22:17,546 autoreload 24080 15712 Watching for file changes with StatReloader
INFO 2024-03-27 20:22:23,122 basehttp 24080 15960 "GET /taskApp/main/ HTTP/1.1" 200 238
INFO 2024-03-27 20:22:47,595 autoreload 24080 15712 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksApp\views.py changed, reloading.
INFO 2024-03-27 20:22:48,001 autoreload 21352 21412 Watching for file changes with StatReloader
INFO 2024-03-27 20:22:52,662 basehttp 21352 8348 "GET /taskApp/main/ HTTP/1.1" 200 252
INFO 2024-03-27 20:25:32,831 autoreload 21352 21412 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksApp\views.py changed, reloading.
INFO 2024-03-27 20:25:33,420 autoreload 2952 21944 Watching for file changes with StatReloader
INFO 2024-03-27 20:25:49,112 basehttp 2952 22036 "GET /taskApp/about/ HTTP/1.1" 200 215
INFO 2024-03-28 00:31:19,107 autoreload 14268 5016 Watching for file changes with StatReloader
WARNING 2024-03-28 00:31:27,589 log 14268 23776 Not Found: /orders/
WARNING 2024-03-28 00:31:27,590 basehttp 14268 23776 "GET /orders/ HTTP/1.1" 404 2102
WARNING 2024-03-28 00:31:31,787 log 14268 23776 Not Found: /
WARNING 2024-03-28 00:31:31,788 basehttp 14268 23776 "GET / HTTP/1.1" 404 2063
WARNING 2024-03-28 00:31:36,196 log 14268 6084 Not Found: /tasks/
WARNING 2024-03-28 00:31:36,197 basehttp 14268 6084 "GET /tasks/ HTTP/1.1" 404 2099
WARNING 2024-03-28 00:31:39,401 log 14268 6084 Not Found: /trows
WARNING 2024-03-28 00:31:39,403 basehttp 14268 6084 "GET /trows HTTP/1.1" 404 2096
INFO 2024-03-28 00:32:56,223 autoreload 14268 5016 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\seminars\urls.py changed, reloading.
INFO 2024-03-28 00:32:56,887 autoreload 22912 13216 Watching for file changes with StatReloader
INFO 2024-03-28 00:33:01,536 basehttp 22912 23448 "GET /tasksapp/trows HTTP/1.1" 301 0
ERROR 2024-03-28 00:33:01,698 log 22912 23996 Internal Server Error: /tasksapp/trows/
Traceback (most recent call last):
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py", line 18, in trows
    result = choice['орёл', 'решка']
TypeError: 'method' object is not subscriptable
ERROR 2024-03-28 00:33:01,700 basehttp 22912 23996 "GET /tasksapp/trows/ HTTP/1.1" 500 65515
INFO 2024-03-28 00:36:23,223 autoreload 22912 13216 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-28 00:36:23,933 autoreload 6024 13080 Watching for file changes with StatReloader
INFO 2024-03-28 00:37:58,667 autoreload 6024 13080 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-28 00:37:59,114 autoreload 18548 19988 Watching for file changes with StatReloader
ERROR 2024-03-28 00:38:03,899 log 18548 11776 Internal Server Error: /tasksapp/trows/
Traceback (most recent call last):
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py", line 19, in trows
    trows = Throws(res_trows=result, time_trows=datetime_trows)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Throws() got unexpected keyword arguments: 'res_trows', 'time_trows'
ERROR 2024-03-28 00:38:03,901 basehttp 18548 11776 "GET /tasksapp/trows/ HTTP/1.1" 500 72892
INFO 2024-03-28 00:39:17,557 autoreload 18548 19988 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\models.py changed, reloading.
INFO 2024-03-28 00:39:18,119 autoreload 11068 13212 Watching for file changes with StatReloader
INFO 2024-03-28 00:39:38,020 autoreload 19396 18068 Watching for file changes with StatReloader
ERROR 2024-03-28 00:39:44,186 log 19396 10312 Internal Server Error: /tasksapp/trows/
Traceback (most recent call last):
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py", line 19, in trows
    trows = Throws(res_trows=result, time_trows=datetime_trows)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Throws() got unexpected keyword arguments: 'res_trows', 'time_trows'
ERROR 2024-03-28 00:39:44,188 basehttp 19396 10312 "GET /tasksapp/trows/ HTTP/1.1" 500 72903
INFO 2024-03-28 00:40:46,216 autoreload 19396 18068 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-28 00:40:46,628 autoreload 14740 19828 Watching for file changes with StatReloader
ERROR 2024-03-28 00:40:56,332 log 14740 12884 Internal Server Error: /tasksapp/trows/
Traceback (most recent call last):
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py", line 21, in trows
    trows = Throws(res_trows=result, time_trows=datetime_trows)
  File "C:\Users\chern\Documents\PythonCourse\DjangoCourse\venv\lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Throws() got unexpected keyword arguments: 'res_trows', 'time_trows'
ERROR 2024-03-28 00:40:56,333 basehttp 14740 12884 "GET /tasksapp/trows/ HTTP/1.1" 500 72847
INFO 2024-03-28 00:42:22,644 autoreload 14740 19828 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-28 00:42:23,076 autoreload 21064 14232 Watching for file changes with StatReloader
WARNING 2024-03-28 00:42:31,775 log 21064 9560 Not Found: /tasksapp/trows/
WARNING 2024-03-28 00:42:31,776 basehttp 21064 9560 "GET /tasksapp/trows/ HTTP/1.1" 404 2725
INFO 2024-03-28 00:43:01,075 views 21064 16700 throws successful
INFO 2024-03-28 00:43:01,076 basehttp 21064 16700 "GET /tasksapp/throws/ HTTP/1.1" 200 89
INFO 2024-03-28 00:43:42,669 autoreload 21064 14232 C:\Users\chern\Documents\PythonCourse\DjangoCourse\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-28 00:43:43,254 autoreload 21612 17256 Watching for file changes with StatReloader
INFO 2024-03-28 00:43:51,096 views 21612 10808 throws successful
INFO 2024-03-28 00:43:51,097 basehttp 21612 10808 "GET /tasksapp/throws/ HTTP/1.1" 200 110
INFO 2024-03-28 00:43:54,034 views 21612 10808 throws successful
INFO 2024-03-28 00:43:54,034 basehttp 21612 10808 "GET /tasksapp/throws/ HTTP/1.1" 200 110
INFO 2024-03-28 00:43:54,913 views 21612 13348 throws successful
INFO 2024-03-28 00:43:54,914 basehttp 21612 13348 "GET /tasksapp/throws/ HTTP/1.1" 200 110
INFO 2024-03-28 00:43:55,604 views 21612 13348 throws successful
INFO 2024-03-28 00:43:55,605 basehttp 21612 13348 "GET /tasksapp/throws/ HTTP/1.1" 200 110
INFO 2024-03-28 00:43:56,355 views 21612 13348 throws successful
INFO 2024-03-28 00:43:56,355 basehttp 21612 13348 "GET /tasksapp/throws/ HTTP/1.1" 200 108
INFO 2024-03-28 00:43:58,067 views 21612 13348 throws successful
INFO 2024-03-28 00:43:58,068 basehttp 21612 13348 "GET /tasksapp/throws/ HTTP/1.1" 200 108
INFO 2024-03-28 00:43:58,849 views 21612 13348 throws successful
INFO 2024-03-28 00:43:58,850 basehttp 21612 13348 "GET /tasksapp/throws/ HTTP/1.1" 200 108
INFO 2024-03-28 00:43:59,783 views 21612 22596 throws successful
INFO 2024-03-28 00:43:59,783 basehttp 21612 22596 "GET /tasksapp/throws/ HTTP/1.1" 200 108
INFO 2024-03-28 00:44:00,386 views 21612 22596 throws successful
INFO 2024-03-28 00:44:00,387 basehttp 21612 22596 "GET /tasksapp/throws/ HTTP/1.1" 200 110
INFO 2024-03-29 21:41:29,746 autoreload 25604 17900 Watching for file changes with StatReloader
INFO 2024-03-29 21:41:53,871 autoreload 21068 26900 Watching for file changes with StatReloader
INFO 2024-03-29 21:42:10,919 views 21068 28468 throws successful
INFO 2024-03-29 21:42:10,920 basehttp 21068 28468 "GET /tasksapp/throws/ HTTP/1.1" 200 110
INFO 2024-03-29 22:04:44,560 autoreload 7688 10692 Watching for file changes with StatReloader
INFO 2024-03-29 22:04:53,184 views 7688 29992 throws successful
INFO 2024-03-29 22:04:53,185 basehttp 7688 29992 "GET /tasksapp/throws/ HTTP/1.1" 200 114
INFO 2024-03-29 22:05:23,372 views 7688 29992 throws successful
INFO 2024-03-29 22:05:23,372 basehttp 7688 29992 "GET /tasksapp/throws/ HTTP/1.1" 200 116
INFO 2024-03-29 22:05:44,912 views 7688 29992 throws successful
INFO 2024-03-29 22:05:44,913 basehttp 7688 29992 "GET /tasksapp/throws/ HTTP/1.1" 200 114
INFO 2024-03-29 22:07:45,067 autoreload 7688 10692 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\models.py changed, reloading.
INFO 2024-03-29 22:07:45,720 autoreload 28540 27336 Watching for file changes with StatReloader
INFO 2024-03-29 22:07:50,824 views 28540 6624 throws successful
INFO 2024-03-29 22:07:50,826 basehttp 28540 6624 "GET /tasksapp/throws/ HTTP/1.1" 200 114
INFO 2024-03-29 22:07:58,458 views 28540 6624 throws successful
INFO 2024-03-29 22:07:58,458 basehttp 28540 6624 "GET /tasksapp/throws/ HTTP/1.1" 200 116
INFO 2024-03-29 22:14:36,851 autoreload 28540 27336 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 22:14:37,505 autoreload 8412 27096 Watching for file changes with StatReloader
INFO 2024-03-29 22:14:42,923 views 8412 25948 throws successful
INFO 2024-03-29 22:14:42,924 basehttp 8412 25948 "GET /tasksapp/throws/ HTTP/1.1" 200 114
INFO 2024-03-29 22:14:46,269 views 8412 25948 throws successful
INFO 2024-03-29 22:14:46,270 basehttp 8412 25948 "GET /tasksapp/throws/ HTTP/1.1" 200 116
INFO 2024-03-29 22:17:18,008 autoreload 8412 27096 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\models.py changed, reloading.
INFO 2024-03-29 22:17:18,620 autoreload 30480 30708 Watching for file changes with StatReloader
INFO 2024-03-29 23:05:27,818 autoreload 30480 30708 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\models.py changed, reloading.
INFO 2024-03-29 23:05:28,597 autoreload 25636 11252 Watching for file changes with StatReloader
INFO 2024-03-29 23:08:38,933 autoreload 6768 26436 Watching for file changes with StatReloader
INFO 2024-03-29 23:09:01,294 autoreload 6768 26436 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\urls.py changed, reloading.
INFO 2024-03-29 23:09:01,891 autoreload 25584 21220 Watching for file changes with StatReloader
INFO 2024-03-29 23:09:32,606 basehttp 25584 29948 "GET /tasksapp/values/ HTTP/1.1" 200 4
INFO 2024-03-29 23:10:17,837 autoreload 25584 21220 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\models.py changed, reloading.
INFO 2024-03-29 23:10:18,460 autoreload 18484 8824 Watching for file changes with StatReloader
INFO 2024-03-29 23:10:25,211 basehttp 18484 28948 "GET /tasksapp/values/ HTTP/1.1" 200 4
INFO 2024-03-29 23:10:26,659 basehttp 18484 28948 "GET /tasksapp/values/ HTTP/1.1" 200 4
INFO 2024-03-29 23:11:50,201 autoreload 18484 8824 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\models.py changed, reloading.
INFO 2024-03-29 23:11:50,933 autoreload 16588 26376 Watching for file changes with StatReloader
INFO 2024-03-29 23:13:16,052 autoreload 16588 26376 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:13:16,668 autoreload 27308 20328 Watching for file changes with StatReloader
ERROR 2024-03-29 23:13:27,622 log 27308 26280 Internal Server Error: /tasksapp/values/
Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py", line 60, in throws_values
    return HttpResponse(str(*res))
                        ^^^^^^^^^
TypeError: str() argument after * must be an iterable, not NoneType
ERROR 2024-03-29 23:13:27,624 basehttp 27308 26280 "GET /tasksapp/values/ HTTP/1.1" 500 64523
INFO 2024-03-29 23:13:57,209 autoreload 27308 20328 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\models.py changed, reloading.
INFO 2024-03-29 23:13:57,852 autoreload 16608 25796 Watching for file changes with StatReloader
ERROR 2024-03-29 23:13:59,520 log 16608 9420 Internal Server Error: /tasksapp/values/
Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py", line 60, in throws_values
    return HttpResponse(str(*res))
                        ^^^^^^^^^
TypeError: str() takes at most 3 arguments (5 given)
ERROR 2024-03-29 23:13:59,522 basehttp 16608 9420 "GET /tasksapp/values/ HTTP/1.1" 500 65017
INFO 2024-03-29 23:14:13,341 autoreload 16608 25796 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:14:13,986 autoreload 17140 17272 Watching for file changes with StatReloader
INFO 2024-03-29 23:14:15,825 basehttp 17140 8764 "GET /tasksapp/values/ HTTP/1.1" 200 451
INFO 2024-03-29 23:15:24,682 autoreload 17140 17272 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:15:25,308 autoreload 6636 20324 Watching for file changes with StatReloader
ERROR 2024-03-29 23:15:27,237 log 6636 28452 Internal Server Error: /tasksapp/values/
Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py", line 59, in throws_values
    res = '\n'.join(Throws.values())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, Throws found
ERROR 2024-03-29 23:15:27,240 basehttp 6636 28452 "GET /tasksapp/values/ HTTP/1.1" 500 64518
ERROR 2024-03-29 23:15:51,206 log 6636 28452 Internal Server Error: /tasksapp/values/
Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py", line 59, in throws_values
    res = Throws.values()
          ^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, Throws found
ERROR 2024-03-29 23:15:51,208 basehttp 6636 28452 "GET /tasksapp/values/ HTTP/1.1" 500 64476
INFO 2024-03-29 23:15:51,218 autoreload 6636 20324 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:15:51,951 autoreload 17216 13652 Watching for file changes with StatReloader
INFO 2024-03-29 23:15:54,652 basehttp 17216 27788 "GET /tasksapp/values/ HTTP/1.1" 200 451
INFO 2024-03-29 23:16:25,250 autoreload 17216 13652 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:16:25,912 autoreload 25324 8216 Watching for file changes with StatReloader
INFO 2024-03-29 23:16:26,116 basehttp 25324 12460 "GET /tasksapp/values/ HTTP/1.1" 200 451
INFO 2024-03-29 23:16:51,216 basehttp 25324 12460 "GET /tasksapp/values/ HTTP/1.1" 200 451
INFO 2024-03-29 23:16:51,532 autoreload 25324 8216 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:16:52,210 autoreload 13420 30596 Watching for file changes with StatReloader
INFO 2024-03-29 23:16:58,497 basehttp 13420 25140 "GET /tasksapp/values/ HTTP/1.1" 200 451
INFO 2024-03-29 23:21:41,025 autoreload 13420 30596 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:21:41,672 autoreload 9844 6104 Watching for file changes with StatReloader
ERROR 2024-03-29 23:21:46,208 log 9844 23156 Internal Server Error: /tasksapp/values/
Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py", line 62, in throws_values
    resp += i + '\n'
            ~~^~~~~~
TypeError: unsupported operand type(s) for +: 'Throws' and 'str'
ERROR 2024-03-29 23:21:46,210 basehttp 9844 23156 "GET /tasksapp/values/ HTTP/1.1" 500 65685
INFO 2024-03-29 23:22:33,609 autoreload 9844 6104 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:22:34,249 autoreload 32 22304 Watching for file changes with StatReloader
INFO 2024-03-29 23:22:39,594 basehttp 32 18420 "GET /tasksapp/values/ HTTP/1.1" 200 456
INFO 2024-03-29 23:22:47,217 basehttp 32 18420 "GET /tasksapp/values/ HTTP/1.1" 200 456
INFO 2024-03-29 23:23:22,829 basehttp 32 18420 "GET /tasksapp/values/ HTTP/1.1" 200 456
INFO 2024-03-29 23:23:23,080 autoreload 32 22304 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\views.py changed, reloading.
INFO 2024-03-29 23:23:23,759 autoreload 7868 29288 Watching for file changes with StatReloader
INFO 2024-03-29 23:23:42,757 basehttp 7868 1712 "GET /tasksapp/values/ HTTP/1.1" 200 456
INFO 2024-03-29 23:33:19,248 autoreload 7868 29288 M:\РАБОТА МИША\Курс Python\django\seminars\tasksapp\models.py changed, reloading.
INFO 2024-03-29 23:33:20,078 autoreload 23492 18936 Watching for file changes with StatReloader
INFO 2024-03-30 19:20:52,056 autoreload 29576 18752 Watching for file changes with StatReloader
INFO 2024-03-30 19:25:28,883 autoreload 29576 18752 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\views.py changed, reloading.
INFO 2024-03-30 19:25:29,464 autoreload 1608 25056 Watching for file changes with StatReloader
WARNING 2024-03-30 19:25:32,662 log 1608 17660 Not Found: /
WARNING 2024-03-30 19:25:32,663 basehttp 1608 17660 "GET / HTTP/1.1" 404 2171
WARNING 2024-03-30 19:25:57,667 log 1608 17660 Not Found: /dz2app/
WARNING 2024-03-30 19:25:57,668 basehttp 1608 17660 "GET /dz2app/ HTTP/1.1" 404 2272
WARNING 2024-03-30 19:26:27,971 log 1608 17660 Not Found: /dz2app
WARNING 2024-03-30 19:26:27,972 basehttp 1608 17660 "GET /dz2app HTTP/1.1" 404 2207
INFO 2024-03-30 19:30:21,119 autoreload 1608 25056 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\urls.py changed, reloading.
INFO 2024-03-30 19:30:21,767 autoreload 19636 884 Watching for file changes with StatReloader
WARNING 2024-03-30 19:31:23,933 log 19636 29028 Not Found: /
WARNING 2024-03-30 19:31:23,934 basehttp 19636 29028 "GET / HTTP/1.1" 404 2171
INFO 2024-03-30 19:31:42,817 basehttp 19636 29028 "GET /tasksapp/values/ HTTP/1.1" 200 456
INFO 2024-03-30 19:33:14,574 autoreload 19636 884 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\urls.py changed, reloading.
INFO 2024-03-30 19:33:15,182 autoreload 10116 24168 Watching for file changes with StatReloader
INFO 2024-03-30 19:33:49,218 basehttp 10116 29364 "GET /dz2app/main/ HTTP/1.1" 200 13
INFO 2024-03-30 19:35:00,361 autoreload 10116 24168 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\views.py changed, reloading.
INFO 2024-03-30 19:35:00,977 autoreload 11868 18116 Watching for file changes with StatReloader
INFO 2024-03-30 23:22:42,886 autoreload 11240 22088 Watching for file changes with StatReloader
ERROR 2024-03-30 23:23:25,549 log 11240 15208 Internal Server Error: /dz2app/cust/
Traceback (most recent call last):
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Администратор\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\views.py", line 19, in create_customer
    customer = Customer(name=name, email=email, phone=phone, address=address)
               ^^^^^^^^
NameError: name 'Customer' is not defined
ERROR 2024-03-30 23:23:25,552 basehttp 11240 15208 "GET /dz2app/cust/ HTTP/1.1" 500 65048
INFO 2024-03-30 23:24:52,243 autoreload 11240 22088 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\views.py changed, reloading.
INFO 2024-03-30 23:24:52,912 autoreload 4876 19372 Watching for file changes with StatReloader
INFO 2024-03-30 23:26:04,361 autoreload 18192 28768 Watching for file changes with StatReloader
INFO 2024-03-31 14:51:27,244 autoreload 8928 24044 Watching for file changes with StatReloader
INFO 2024-03-31 14:51:42,350 autoreload 8928 24044 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\views.py changed, reloading.
INFO 2024-03-31 14:51:42,968 autoreload 2632 13404 Watching for file changes with StatReloader
INFO 2024-03-31 14:51:50,521 autoreload 2632 13404 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\views.py changed, reloading.
INFO 2024-03-31 14:51:51,132 autoreload 27660 29192 Watching for file changes with StatReloader
INFO 2024-03-31 14:51:59,443 basehttp 27660 26360 "GET /dz2app/cust/ HTTP/1.1" 200 48
INFO 2024-03-31 14:53:49,023 autoreload 27660 29192 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\models.py changed, reloading.
INFO 2024-03-31 14:53:49,672 autoreload 18064 20068 Watching for file changes with StatReloader
INFO 2024-03-31 14:54:07,053 autoreload 8016 9432 Watching for file changes with StatReloader
INFO 2024-03-31 14:54:10,655 basehttp 8016 11164 "GET /dz2app/cust/ HTTP/1.1" 200 48
INFO 2024-03-31 14:54:57,388 basehttp 8016 11164 "GET /dz2app/cust/ HTTP/1.1" 200 48
INFO 2024-03-31 14:57:38,189 basehttp 8016 11164 "GET /dz2app/cust/ HTTP/1.1" 200 48
INFO 2024-03-31 14:58:13,064 views 8016 11164 throws successful
INFO 2024-03-31 14:58:13,064 basehttp 8016 11164 "GET /tasksapp/throws/ HTTP/1.1" 200 114
INFO 2024-03-31 15:00:00,696 autoreload 8016 9432 M:\РАБОТА МИША\Курс Python\django\seminars\dz2app\models.py changed, reloading.
INFO 2024-03-31 15:00:01,313 autoreload 24040 19412 Watching for file changes with StatReloader
INFO 2024-03-31 16:52:54,970 autoreload 13188 7392 Watching for file changes with StatReloader
INFO 2024-03-31 16:53:16,658 autoreload 10696 30412 Watching for file changes with StatReloader
INFO 2024-03-31 16:55:11,588 autoreload 13776 9860 Watching for file changes with StatReloader
